# Generated by Django 4.1.7 on 2023-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variants",
            name="image_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
