# Generated by Django 4.1.7 on 2023-03-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_variants_image_id_remove_variants_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variants",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.products",
            ),
        ),
    ]
