# Generated by Django 4.1.7 on 2023-03-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_variants_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="products.brands",
            ),
        ),
    ]
